// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1281: x0 => x0.requestFullscreen(),
      _1282: x0 => x0.exitFullscreen(),
      _1283: (x0,x1) => x0.fetch(x1),
      _1284: x0 => x0.blob(),
      _1285: () => new FileReader(),
      _1286: (x0,x1) => x0.readAsText(x1),
      _1287: (x0,x1) => x0.createElement(x1),
      _1288: (x0,x1) => x0.item(x1),
      _1289: x0 => globalThis.URL.createObjectURL(x0),
      _1290: x0 => x0.click(),
      _1291: (x0,x1) => x0.canPlayType(x1),
      _1304: x0 => x0.preventDefault(),
      _1305: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1306: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1307: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1314: x0 => x0.createReader(),
      _1315: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1315(f,arguments.length,x0) }),
      _1316: (x0,x1) => x0.readEntries(x1),
      _1317: () => new Blob(),
      _1318: (x0,x1,x2,x3) => x0.slice(x1,x2,x3),
      _1319: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1319(f,arguments.length,x0) }),
      _1320: (x0,x1) => x0.file(x1),
      _1321: x0 => x0.webkitGetAsEntry(),
      _1322: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1322(f,arguments.length,x0) }),
      _1323: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1323(f,arguments.length,x0) }),
      _1324: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1324(f,arguments.length,x0) }),
      _1325: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1325(f,arguments.length,x0) }),
      _1334: x0 => globalThis.Wakelock.toggle(x0),
      _1336: (x0,x1) => x0.getItem(x1),
      _1338: (x0,x1,x2) => x0.setItem(x1,x2),
      _1339: Date.now,
      _1341: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1342: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1343: () => new Error().stack,
      _1344: () => typeof dartUseDateNowForTicks !== "undefined",
      _1345: () => 1000 * performance.now(),
      _1346: () => Date.now(),
      _1347: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1348: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1349: () => new WeakMap(),
      _1350: (map, o) => map.get(o),
      _1351: (map, o, v) => map.set(o, v),
      _1352: (exn) => exn.toString(),
      _1353: (exn) => exn.stack,
      _1354: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1355: x0 => new WeakRef(x0),
      _1356: x0 => x0.deref(),
      _1357: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1357(f,arguments.length,x0) }),
      _1358: x0 => new FinalizationRegistry(x0),
      _1360: (x0,x1,x2) => x0.register(x1,x2),
      _1363: () => globalThis.WeakRef,
      _1364: () => globalThis.FinalizationRegistry,
      _1367: s => JSON.stringify(s),
      _1368: s => printToConsole(s),
      _1369: (o, p, r) => o.replaceAll(p, () => r),
      _1370: (o, p, r) => o.replace(p, () => r),
      _1371: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1372: s => s.toUpperCase(),
      _1373: s => s.trim(),
      _1374: s => s.trimLeft(),
      _1375: s => s.trimRight(),
      _1376: (string, times) => string.repeat(times),
      _1377: Function.prototype.call.bind(String.prototype.indexOf),
      _1378: (s, p, i) => s.lastIndexOf(p, i),
      _1379: (string, token) => string.split(token),
      _1380: Object.is,
      _1383: (o, t) => typeof o === t,
      _1384: (o, c) => o instanceof c,
      _1385: o => Object.keys(o),
      _1415: x0 => new Array(x0),
      _1417: x0 => x0.length,
      _1419: (x0,x1) => x0[x1],
      _1420: (x0,x1,x2) => { x0[x1] = x2 },
      _1423: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1425: x0 => new Int8Array(x0),
      _1426: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1428: x0 => new Uint8ClampedArray(x0),
      _1430: x0 => new Int16Array(x0),
      _1432: x0 => new Uint16Array(x0),
      _1434: x0 => new Int32Array(x0),
      _1436: x0 => new Uint32Array(x0),
      _1438: x0 => new Float32Array(x0),
      _1440: x0 => new Float64Array(x0),
      _1464: x0 => x0.random(),
      _1465: (x0,x1) => x0.getRandomValues(x1),
      _1466: () => globalThis.crypto,
      _1467: () => globalThis.Math,
      _1480: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1481: (handle) => clearTimeout(handle),
      _1482: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1483: (handle) => clearInterval(handle),
      _1484: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1485: () => Date.now(),
      _1486: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1487: (x0,x1) => x0.exec(x1),
      _1488: (x0,x1) => x0.test(x1),
      _1489: x0 => x0.pop(),
      _1491: o => o === undefined,
      _1493: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1495: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1496: o => o instanceof RegExp,
      _1497: (l, r) => l === r,
      _1498: o => o,
      _1499: o => o,
      _1500: o => o,
      _1501: b => !!b,
      _1502: o => o.length,
      _1504: (o, i) => o[i],
      _1505: f => f.dartFunction,
      _1506: () => ({}),
      _1507: () => [],
      _1509: () => globalThis,
      _1510: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1512: (o, p) => o[p],
      _1513: (o, p, v) => o[p] = v,
      _1514: (o, m, a) => o[m].apply(o, a),
      _1516: o => String(o),
      _1517: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1518: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1518(f,arguments.length,x0) }),
      _1519: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1519(f,arguments.length,x0,x1) }),
      _1520: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1521: o => [o],
      _1522: (o0, o1) => [o0, o1],
      _1523: (o0, o1, o2) => [o0, o1, o2],
      _1524: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1525: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1526: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1529: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1530: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1531: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1532: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1533: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1534: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1535: x0 => new ArrayBuffer(x0),
      _1536: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1538: x0 => x0.index,
      _1540: x0 => x0.flags,
      _1541: x0 => x0.multiline,
      _1542: x0 => x0.ignoreCase,
      _1543: x0 => x0.unicode,
      _1544: x0 => x0.dotAll,
      _1545: (x0,x1) => { x0.lastIndex = x1 },
      _1546: (o, p) => p in o,
      _1547: (o, p) => o[p],
      _1548: (o, p, v) => o[p] = v,
      _1561: x0 => x0.toArray(),
      _1564: x0 => x0.entries(),
      _1573: x0 => x0.getAvailability(),
      _1575: (x0,x1) => x0.requestDevice(x1),
      _1581: x0 => x0.uuids,
      _1582: x0 => x0.manufacturerData,
      _1583: x0 => x0.serviceData,
      _1584: x0 => x0.name,
      _1585: x0 => x0.rssi,
      _1586: x0 => x0.txPower,
      _1587: x0 => x0.appearance,
      _1588: x0 => x0.value,
      _1590: x0 => x0.connected,
      _1591: x0 => x0.connect(),
      _1592: x0 => x0.disconnect(),
      _1595: x0 => x0.getPrimaryServices(),
      _1596: x0 => x0.broadcast,
      _1597: x0 => x0.read,
      _1598: x0 => x0.writeWithoutResponse,
      _1599: x0 => x0.write,
      _1600: x0 => x0.notify,
      _1601: x0 => x0.indicate,
      _1602: x0 => x0.authenticatedSignedWrites,
      _1605: x0 => x0.id,
      _1606: x0 => x0.name,
      _1607: x0 => x0.gatt,
      _1608: x0 => x0.watchAdvertisements(),
      _1609: (x0,x1) => x0.watchAdvertisements(x1),
      _1611: x0 => x0.watchingAdvertisements,
      _1614: x0 => ({signal: x0}),
      _1625: x0 => x0.bluetooth,
      _1627: x0 => x0.uuid,
      _1628: x0 => x0.properties,
      _1629: x0 => x0.value,
      _1635: (x0,x1) => x0._writeValue(x1),
      _1636: (x0,x1) => x0.writeValueWithResponse(x1),
      _1637: (x0,x1) => x0.writeValueWithoutResponse(x1),
      _1638: x0 => x0.startNotifications(),
      _1639: x0 => x0.stopNotifications(),
      _1648: x0 => x0.uuid,
      _1652: x0 => x0.getCharacteristics(),
      _1662: () => ({}),
      _1677: () => ({}),
      _1679: () => new AbortController(),
      _1681: x0 => globalThis.AbortSignal.abort(x0),
      _1682: () => new XMLHttpRequest(),
      _1683: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1687: x0 => x0.send(),
      _1690: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1690(f,arguments.length,x0) }),
      _1691: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1691(f,arguments.length,x0) }),
      _1696: (x0,x1) => new WebSocket(x0,x1),
      _1697: (x0,x1) => x0.send(x1),
      _1698: (x0,x1,x2) => x0.close(x1,x2),
      _1700: x0 => x0.close(),
      _1701: (x0,x1) => x0.appendChild(x1),
      _1702: (x0,x1) => x0.item(x1),
      _1705: x0 => ({type: x0}),
      _1706: (x0,x1) => new Blob(x0,x1),
      _1707: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1717: (x0,x1) => x0.append(x1),
      _1718: (x0,x1) => x0.append(x1),
      _1719: x0 => ({xhrSetup: x0}),
      _1720: x0 => new Hls(x0),
      _1721: () => globalThis.Hls.isSupported(),
      _1723: (x0,x1) => x0.loadSource(x1),
      _1724: (x0,x1) => x0.attachMedia(x1),
      _1725: x0 => x0.pause(),
      _1726: (x0,x1) => x0.end(x1),
      _1728: x0 => x0.load(),
      _1730: x0 => x0.play(),
      _1735: (x0,x1) => x0.key(x1),
      _1736: o => o instanceof Array,
      _1740: (a, l) => a.length = l,
      _1741: a => a.pop(),
      _1742: (a, i) => a.splice(i, 1),
      _1744: (a, s, e) => a.slice(s, e),
      _1746: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _1747: a => a.length,
      _1749: (a, i) => a[i],
      _1750: (a, i, v) => a[i] = v,
      _1752: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _1753: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _1754: o => o instanceof DataView,
      _1755: o => o instanceof Uint8Array,
      _1756: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _1757: o => o instanceof Int8Array,
      _1758: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _1759: o => o instanceof Uint8ClampedArray,
      _1760: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _1761: o => o instanceof Uint16Array,
      _1762: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _1763: o => o instanceof Int16Array,
      _1764: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _1765: o => o instanceof Uint32Array,
      _1766: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _1767: o => o instanceof Int32Array,
      _1768: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _1770: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _1771: o => o instanceof Float32Array,
      _1772: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _1773: o => o instanceof Float64Array,
      _1774: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _1775: (t, s) => t.set(s),
      _1776: l => new DataView(new ArrayBuffer(l)),
      _1777: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _1779: o => o.buffer,
      _1780: o => o.byteOffset,
      _1781: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _1782: (b, o) => new DataView(b, o),
      _1783: (b, o, l) => new DataView(b, o, l),
      _1784: Function.prototype.call.bind(DataView.prototype.getUint8),
      _1785: Function.prototype.call.bind(DataView.prototype.setUint8),
      _1786: Function.prototype.call.bind(DataView.prototype.getInt8),
      _1787: Function.prototype.call.bind(DataView.prototype.setInt8),
      _1788: Function.prototype.call.bind(DataView.prototype.getUint16),
      _1789: Function.prototype.call.bind(DataView.prototype.setUint16),
      _1790: Function.prototype.call.bind(DataView.prototype.getInt16),
      _1791: Function.prototype.call.bind(DataView.prototype.setInt16),
      _1792: Function.prototype.call.bind(DataView.prototype.getUint32),
      _1793: Function.prototype.call.bind(DataView.prototype.setUint32),
      _1794: Function.prototype.call.bind(DataView.prototype.getInt32),
      _1795: Function.prototype.call.bind(DataView.prototype.setInt32),
      _1798: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _1799: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _1800: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _1801: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _1802: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _1803: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _1804: Function.prototype.call.bind(Number.prototype.toString),
      _1805: Function.prototype.call.bind(BigInt.prototype.toString),
      _1806: Function.prototype.call.bind(Number.prototype.toString),
      _1807: (d, digits) => d.toFixed(digits),
      _1912: (x0,x1) => { x0.responseType = x1 },
      _1913: x0 => x0.response,
      _1989: x0 => x0.style,
      _2561: x0 => x0.videoWidth,
      _2562: x0 => x0.videoHeight,
      _2591: x0 => x0.error,
      _2593: (x0,x1) => { x0.src = x1 },
      _2602: x0 => x0.buffered,
      _2605: x0 => x0.currentTime,
      _2606: (x0,x1) => { x0.currentTime = x1 },
      _2607: x0 => x0.duration,
      _2608: x0 => x0.paused,
      _2611: x0 => x0.playbackRate,
      _2612: (x0,x1) => { x0.playbackRate = x1 },
      _2623: (x0,x1) => { x0.controls = x1 },
      _2624: x0 => x0.volume,
      _2625: (x0,x1) => { x0.volume = x1 },
      _2626: x0 => x0.muted,
      _2627: (x0,x1) => { x0.muted = x1 },
      _2643: x0 => x0.message,
      _2717: x0 => x0.length,
      _2913: (x0,x1) => { x0.accept = x1 },
      _2927: x0 => x0.files,
      _2953: (x0,x1) => { x0.multiple = x1 },
      _2971: (x0,x1) => { x0.type = x1 },
      _3220: x0 => x0.src,
      _3221: (x0,x1) => { x0.src = x1 },
      _3223: (x0,x1) => { x0.type = x1 },
      _3227: (x0,x1) => { x0.async = x1 },
      _3241: (x0,x1) => { x0.charset = x1 },
      _3672: x0 => x0.items,
      _3675: (x0,x1) => x0[x1],
      _3679: x0 => x0.length,
      _3685: x0 => x0.dataTransfer,
      _3689: () => globalThis.window,
      _3751: x0 => x0.navigator,
      _3822: (x0,x1) => { x0.ondragenter = x1 },
      _3824: (x0,x1) => { x0.ondragleave = x1 },
      _3826: (x0,x1) => { x0.ondragover = x1 },
      _3830: (x0,x1) => { x0.ondrop = x1 },
      _4015: x0 => x0.localStorage,
      _4140: x0 => x0.userAgent,
      _4141: x0 => x0.vendor,
      _4191: x0 => x0.data,
      _4348: x0 => x0.length,
      _4565: x0 => x0.readyState,
      _4574: x0 => x0.protocol,
      _4578: (x0,x1) => { x0.binaryType = x1 },
      _4581: x0 => x0.code,
      _4582: x0 => x0.reason,
      _6249: x0 => x0.type,
      _6289: x0 => x0.signal,
      _6299: x0 => x0.length,
      _6359: () => globalThis.document,
      _6418: x0 => x0.documentElement,
      _6441: x0 => x0.head,
      _6481: x0 => x0.fullscreenElement,
      _6795: (x0,x1) => { x0.innerHTML = x1 },
      _6798: x0 => x0.children,
      _7104: x0 => x0.clientX,
      _7105: x0 => x0.clientY,
      _8299: x0 => x0.size,
      _8300: x0 => x0.type,
      _8307: x0 => x0.name,
      _8308: x0 => x0.lastModified,
      _8313: x0 => x0.length,
      _8319: x0 => x0.result,
      _10949: (x0,x1) => { x0.border = x1 },
      _11391: (x0,x1) => { x0.height = x1 },
      _12081: (x0,x1) => { x0.width = x1 },
      _12450: x0 => x0.message,
      _13134: x0 => x0.isDirectory,
      _13135: x0 => x0.name,
      _13136: x0 => x0.fullPath,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
